### ISSUE TITLE
[XCOME_VALUE_UNMATCH]: vai_c_xir compiled error from pytorch model

### ISSUE THREAD

**Issue by JackzhangLOVEcode** [Xilinx/Vitis-AI#891] opened 2022-06-26 04:12 UTC
I quantified two models, when compile them by vai_c_xir, one was ok, another compiled failed, here is error information
![image](https://user-images.githubusercontent.com/35070703/175798922-be92df9a-a105-4f98-8fd6-5d7cad0d868b.png)
Anyone knows what the error information means? All suggestions are welcome!!

**Comment by wanghong4compiler** [comment] 2022-06-27 11:29
Hi @JackzhangLOVEcode ,
Could you share the model file build/quant_model_en/Encoder_int.xmodel, so that I can reproduce this issue?

**Comment by JackzhangLOVEcode** [comment] 2022-06-27 11:59
> 

OK ！ Encoder_int.xmodel compiled fine,  Decoder_int.xmodel compiled failed,  here is it，thank you for reply
[Decoder_int.zip](https://github.com/Xilinx/Vitis-AI/files/8991704/Decoder_int.zip)

**Comment by sh39o** [comment] 2022-08-10 07:20
Hi @JackzhangLOVEcode 
The bug has been fixed in the new patch https://github.com/Xilinx/Vitis-AI/blob/master/docs/quick-start/install/Vitis%20AI%202.5%20Aug%202022%20Patch.md. 
"Fixed a compiler bug to support concatenate operator cascaded with multiple reshape operators" 
Thank you for reporting the bug!

**Comment by qianglin-xlnx** [comment] 2022-08-31 05:49
Closing since no activity for more than 2 weeks, please reopen if you still have question, thanks

**Closed by qianglin-xlnx** 2022-08-31 05:49 UTC
