### ISSUE TITLE
is the VCK190 image correct?

### ISSUE THREAD

**Issue by giovanniguasti** [Xilinx/Vitis-AI#797] opened 2022-05-11 09:29 UTC
This problem was found [here](https://github.com/Xilinx/Vitis-AI/tree/master/Whole-App-Acceleration/apps/adas_detection)
the WAA ADAS example for VCK190 has this VCK190 image:
https://www.xilinx.com/member/forms/download/design-license-xef.html?filename=xilinx-vck190-dpu-v2020.2-v1.4.0.img.gz
but the new one for production silicon should be
https://www.xilinx.com/member/forms/download/design-license-xef.html?filename=xilinx-vck190-dpu-v2021.2-v2.0.0.img.gz

is this a typo?

**Comment by sumitn-xilinx** [comment] 2022-05-13 06:18
Not a typo, it's actually using the old version.
This is going to be fixed in VAI 2.5.

**Comment by qianglin-xlnx** [comment] 2022-09-09 08:49
Hi @giovanniguasti 
The issue is fixed in VAI2.5. Please refer to https://github.com/Xilinx/Vitis-AI/tree/master/examples/Whole-App-Acceleration/apps/adas_detection#1-setting-sd-card

**Closed by qianglin-xlnx** 2022-09-09 08:49 UTC
