### ISSUE TITLE
quantization

### ISSUE THREAD

**Issue by dingguodong-826** [Xilinx/Vitis-AI#322] opened 2021-03-08 02:19 UTC
Hello, I encountered this problem while quantifying the PyTorch model, thank you!

![image](https://user-images.githubusercontent.com/57715990/110265951-b5485c00-7ff7-11eb-89c9-c6cd0367d8d1.png)

**Comment by niuxjxlnx** [comment] 2021-03-08 07:47
hi, @dingguodong-826:

I noticed you met several problems when you quantize your inception-v3 model(another issue: https://github.com/Xilinx/Vitis-AI/issues/316). But we can quantize offical inception-v3 model successfully.  
So you can paste your file quantize.py here? I can help analysis the root cause.

**Comment by dingguodong-826** [comment] 2021-03-08 08:01
Hello, I have uploaded the relevant files for quantification (weights, common.py; Quant.py), thank you for your guidance
Note: I have made changes to some layers of Inceptionv3. I will email you the weights of the training if needed

[inception3_quant.zip](https://github.com/Xilinx/Vitis-AI/files/6099753/inception3_quant.zip)

**Comment by niuxjxlnx** [comment] 2021-03-08 08:22
hi, @dingguodong-826:

Can I send your quant.py, common.py and weights to me (niuxj@xilinx.com)?

**Comment by dingguodong-826** [comment] 2021-03-08 08:29
Yes, please leave your email address for me

**Comment by carrotandjzy** [comment] 2021-03-11 03:54
hi, @dingguodong-826:
We have found the root cause of your isssue. There are two consecutive slice operators in the generated quantizable module , the quantizer can't handle this situation. This issue will be solved in the next release.

**Comment by hoadv-qh** [comment] 2021-03-21 07:34
> hi, @dingguodong-826:
> We have found the root cause of your isssue. There are two consecutive slice operators in the generated quantizable module , the quantizer can't handle this situation. This issue will be solved in the next release.

Hi @carrotandjzy:
I got same issue when trying to quantize [route] layer of yolov4-tiny with attribute as below.
<pre>
[route]
layers=-1
groups=2
group_id=1
</pre> 

* Above [route] layer requires to slice output of previous layer to feed to next layer
* I checked model class (output by Vitis AI Quantizer for Pytorch). It shows there are 2 consecutive slices.
<pre>
self.module_54 = py_nndct.nn.Module('shape')
self.module_55 = py_nndct.nn.Module('tensor')
self.module_56 = py_nndct.nn.Module('const')
self.module_58 = py_nndct.nn.Int()
self.module_59 = py_nndct.nn.strided_slice() <----
self.module_60 = py_nndct.nn.strided_slice() <----
</pre>

My question: Is there any workaround to treat 2 consecutive slice operators while waiting for next release of Vitis AI?

**Comment by YanxianChen** [comment] 2021-04-09 08:14
Hi @hoadv-qh , have you found some ways to replace the slice operator in caffe or pytorch?

**Comment by niuxjxlnx** [comment] 2022-02-21 04:06
The problem has been fixed in VAI 1.4/1.4.1 and 2.0 version. Will close it if no more response.

**Closed** 2022-02-22 08:26 UTC
