### ISSUE TITLE
about the pytorch add!!!!!!!! what's wrong?!!!

### ISSUE THREAD

**Issue by white0dew** [Xilinx/Vitis-AI#671] opened 2022-02-09 09:45 UTC
when i tested this model:
![8 WCURP1$SXFQ6 )`PEJQ35](https://user-images.githubusercontent.com/49017390/153170121-477472d4-3deb-4c90-b438-b45053d8a404.png)

the process of calib is ok.

but it occured in the "test --deploy":
![8QK_$YAB3Z_$5GNWRPQVMFO](https://user-images.githubusercontent.com/49017390/153170298-b6903c55-5713-4071-b0a2-c18f057e9a52.png)

This is confused me very very bad,  how can i correct it?
I ony want to find a way to implement the hardsigmoid , pls help me ,Thank you very much!

**Comment by Alexiazzf** [comment] 2022-02-22 08:55
Hi @white0dew ,

Which version of Vitis-AI you used? I tested your example and it can deploy well.

**Comment by white0dew** [comment] 2022-02-22 08:59
> 

Hi @Alexiazzf 
My Vitis-AI is 1.4, could you upload your deployed xmodel?
I had tested Vitis-AI 2.0 , and I will get segmentation when I test any model.

**Comment by Alexiazzf** [comment] 2022-02-22 09:09
Hi @white0dew ,

Here is my xmodel:
[Model_int (5).zip](https://github.com/Xilinx/Vitis-AI/files/8115184/Model_int.5.zip)

**Comment by white0dew** [comment] 2022-02-22 09:11
Hi @Alexiazzf 
Which version of Vitis-AI you used? 
Now I am very confused....

**Comment by Alexiazzf** [comment] 2022-02-22 09:18
Hi @white0dew ,

I use Vitis-AI 2.0.

**Comment by white0dew** [comment] 2022-02-22 13:33
Thanks @Alexiazzf 
I will test the Vitis-AI tomorrow again, your Docker is GPU version?

**Comment by Alexiazzf** [comment] 2022-02-23 08:18
Hi @white0dew ,

Yes, my docker is GPU version.

**Comment by Alexiazzf** [comment] 2022-02-25 03:17
Hi @white0dew ,

Have you solved your problem? In Vitis-AI 1.4, you can change your scalar “1” in `torch.add(x, 1)` to a Tensor. There is a bug in Vitis-AI1.4 when a tensor add a scalar directly. And it has been fixed in Vitis-AI 2.0.

**Comment by white0dew** [comment] 2022-02-25 06:58
> Hi @white0dew ,
> 
> Have you solved your problem? In Vitis-AI 1.4, you can change your scalar “1” in `torch.add(x, 1)` to a Tensor. There is a bug in Vitis-AI1.4 when a tensor add a scalar directly. And it has been fixed in Vitis-AI 2.0.
> 
> When your problem have solved, please let me know, thanks.

Very Sad, when I used the Vitis-Ai 2.0 there is a problem which confused me very much.
![image](https://user-images.githubusercontent.com/49017390/155669176-5a86663c-147a-497e-8e9f-92eb3ff40117.png)

No matter I quant which model ， this problem always occur......
Can you help me?

**Comment by white0dew** [comment] 2022-02-25 06:58
And My Vitis-Ai image is CPU version ,which is downloaded from your docker hub.

**Comment by Alexiazzf** [comment] 2022-02-25 07:08
Hi @white0dew,

I think "segmentation fault" is not caused by quantization of `torch.add(x, 1)`. What kind of CPU and GPUs are you using?

**Comment by white0dew** [comment] 2022-02-25 07:21
> Hi @white0dew,
> 
> I think "segmentation fault" is not caused by quantization of `torch.add(x, 1)`. What kind of CPU and GPUs are you using? And what kind of operating system are you using? And which version? Do you use original conda environment in docker? Or you made your own conda environment in Vitis-AI docker?

Thanks! I solve this problem which is caued by tensot.to(cuda) .
PS:Beacuse My version is cpu...

But when i compile model to KV260 , i find that the add op is run on cpu, why?

So there is no way for me to implement a hard_sigmoid op on KV260?

**Comment by Alexiazzf** [comment] 2022-02-25 07:26
Hi @white0dew ,

Only VCK190 support HardSigmoid compiling. Other hardware will transfer HardSigmoid to CPU automatically.

**Comment by white0dew** [comment] 2022-02-25 07:28
> Hi @white0dew ,
> 
> Only VCK190 support HardSigmoid compiling. Other hardware will transfer HardSigmoid to CPU automatically.

Thank you very much , then  i consider use another op to replace the h_sigmoid.

**Closed** 2022-02-25 07:30 UTC
