### ISSUE TITLE
error while quantization yolov5 tensorflow2 keras model

### ISSUE THREAD

**Issue by curioushakya** [Xilinx/Vitis-AI#742] opened 2022-04-04 10:02 UTC
I got following error while quantizing yolov5 model in tensorflow2 
```
File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/keras/engine/functional.py", line 1163, in _deserialize_keras_tensor

layer = layer_map[layer_name]

KeyError: 'activation_4'

```
I am looking for possible hints and quantizing solutions .
I am following this link for the training the model (github.com/jahongir7174/YOLOv5-tf) .This model is working fine in GPU (whole model  H5 format ). 
I am using vitis ai 2.0 for quantization and compilation .
P.S:I have followed this git issues for possible solutions but not get the solution :
https://github.com/Xilinx/Vitis-AI/issues?q=yolov5+ 
Thanks in advance!

**Comment by xieyi4650** [comment] 2022-04-06 05:36
@curioushakya 
Can you provide code and files so that we can reproduce the error

**Comment by AfifaIshtiaq** [comment] 2022-05-04 14:23
Hi I got the following error in tf2 .h5 model while quantizing 

  path = get_file('frame_esn0_0-0.npz',origin=origin_folder + 'frame_esn0_0-0.npz')
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/data_utils.py", line 251, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/urllib/request.py", line 511, in open
    req = Request(fullurl, data)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'data_capture_qpsk/frame_esn0_0-0.npz'

**Comment by chuo1** [comment] 2022-07-21 08:04
> g vitis ai 2.0 for quantization and compilation .

I tried to quantify it on vai2.5 with the model you provided(model_s.h5), and the result is normal. Would you also try the latest vai2.5 to see if there are fixes and updates?

**Comment by renjiangyong** [comment] 2022-09-06 07:09
the issue is open for a long time, I will close it , you can reopen it when you still have problem

**Closed by renjiangyong** 2022-09-06 07:09 UTC
