### ISSUE TITLE
Facing issue with neptune

### ISSUE THREAD

**Issue by durgabhavaniv** [Xilinx/Vitis-AI#501] opened 2021-08-05 14:13 UTC
I am trying to run Neptune without any errors, but am not able to get output in the browser. [https://github.com/Xilinx/Vitis-AI/tree/v1.3.2/demo/neptune](https://github.com/Xilinx/Vitis-AI/tree/v1.3.2/demo/neptune)
Output log:
![Screenshot 2021-08-05 19:34:43](https://user-images.githubusercontent.com/42232855/128364519-73016868-573e-4e2b-a944-f60dc3f3de44.png)
Bowser log:
![Screenshot 2021-08-05 19:35:13](https://user-images.githubusercontent.com/42232855/128364573-383db7e7-a0ba-4b3b-aa42-be76f6601bb7.png)

**Comment by varunsh-xilinx** [comment] 2021-08-17 23:22
I don't see what errors you got but I got some missing package errors when I tried it using some 1.3.* containers. It looks like there are some conflicts in conda in the newer versions of the docker container that interfere with Neptune. However, I was able to start the server with an earlier version of Vitis-AI.

```bash
# on host, clone the Vitis-AI repo
$ cd Vitis-AI
$ git checkout v1.1
$ ./docker_run.sh xilinx/vitis-ai-cpu:1.1.56

# in container
$ conda activate vitis-ai-neptune
$ cd alveo/neptune
$ ./run.sh
```

The server GUI should be visible in the browser on port 8998.

**Comment by renjiangyong** [comment] 2022-09-06 07:03
@durgabhavaniv @varunsh-xilinx  , you can use Vitis-AI 2.5 for experiment.  The issue is open for a long time, I will close it, you can reopen it when you need.

**Closed by renjiangyong** 2022-09-06 07:03 UTC
