### ISSUE TITLE
PyTorch Scalar-Tensor ElementWise Ops: Cause vai_c_xir Fatal Error

### ISSUE THREAD

**Issue by Hamptonjc** [Xilinx/Vitis-AI#1015] opened 2022-09-15 19:04 UTC
When using element wise operations between a tensor and a scalar, the Vitis AI model compiler fails to compile the model with error:

```
[UNILOG][FATAL][XIR_INVALID_ARG_OCCUR][Invalid arg occurence!] The channel of weights should be equal to the channel of input in depthwise conv2d
```
Operations:
```python
class Mul2(torch.nn.Module):

    def __init__(self) -> None:
        super().__init__()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return torch.mul(x, 2.0)

class Sub1(torch.nn.Module):

    def __init__(self) -> None:
        super().__init__()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return torch.add(x, -1.0)

class OneSubTensor(torch.nn.Module):

    def __init__(self) -> None:
        super().__init__()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = torch.mul(x, -1.0)
        return torch.add(x, 1.0)
```
I've also tried to use scalar tensor objects:
```python
class Mul2(torch.nn.Module):

    def __init__(self) -> None:
        super().__init__()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return torch.mul(x, torch.tensor(2.0))

class Sub1(torch.nn.Module):

    def __init__(self) -> None:
        super().__init__()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return torch.add(x, torch.tensor(-1.0))

class OneSubTensor(torch.nn.Module):

    def __init__(self) -> None:
        super().__init__()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = torch.mul(x, torch.tensor(-1.0))
        return torch.add(x, torch.tensor(1.0))
```
However this results in the same error.

Any ideas?

**Comment by huisunCompiler** [comment] 2022-09-20 02:05
Hi @Hamptonjc ,
The element wise operation between a tensor and a scalar is not supported in xir. 
The mul between an data array and a constant array will be transferred into a depth-wise convolution in DPU. And the depth-wise conv requires that the channel length of input data and weight data are the same. 
e.g., input shape (1, 1080, 1920, 64), weight shape (64).
Thus, you can try x = torch.mul(x, torch.tensor(1.0).repeat(x.shape[-1])) to see whether the problem is solved.

**Closed** 2022-11-14 12:05 UTC
