### ISSUE TITLE
runtime error: F1011 17:35:48.648877  1409 buffer_object_xrt_imp.cpp:74] Check failed: bo_ != XRT_NULL_BO  allocation failure:  xrt_.handle 0x28fea590 xrt_.device_id 0 size  419795968 xrt_.flags 0x1000000

### ISSUE THREAD

**Issue by linbaiwpi** [Xilinx/Vitis-AI#552] opened 2021-10-11 18:20 UTC
I compiled my own network targeting to ZCU102/104. Everything is fine during compilation. But when running on the board, I got the following errors:

**WARNING: Logging before InitGoogleLogging() is written to STDERR
F1011 17:35:48.648877  1409 buffer_object_xrt_imp.cpp:74] Check failed: bo_ != XRT_NULL_BO  allocation failure:  xrt_.handle 0x28fea590 xrt_.device_id 0 size  419795968 xrt_.flags 0x1000000
*** Check failure stack trace: ***
Aborted (core dumped)**

Does anyone have idea about why it happens?

**Comment by yongshengxu-xlnx** [comment] 2022-02-23 03:05
Hi, @linbaiwpi 
The problem initially appears to be that the model is too large and there is not enough memory on the board to load it. You can try to compress your model and try again. Or provide us with the model and we try to reproduce the problem and determine the cause.

**Comment by qianglin-xlnx** [comment] 2022-03-02 05:46
Hi @linbaiwpi 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.

**Closed by qianglin-xlnx** 2022-03-02 05:46 UTC

**Comment by ranirachel2021** [comment] 2023-02-08 07:12
Hi @yongshengxu-xlnx 

I am facing a similar issue while executing custom trained yolov3 model using Vitis-AI-Library API.

**_root@xilinx-zcu102-2020_2:~/Vitis-AI/demo/Vitis-AI-Library/samples/yolov3# ./test_video_yolov3 yolov3zcu 0 -t 6

** (test_video_yolov3:1310): CRITICAL **: 13:24:22.707: gst_v4l2_object_destroy: assertion 'v4l2object != NULL' failed

** (test_video_yolov3:1310): CRITICAL **: 13:24:23.281: gst_v4l2_object_destroy: assertion 'v4l2object != NULL' failed
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1213 13:24:27.990424  1310 buffer_object_xrt_imp.cpp:74] Check failed: bo_ != XRT_NULL_BO  allocation failure:  xrt_.handle 0xaaaaceaedc80 xrt_.device_id 0 size  5914624 xrt_.flags 0x1000000
*** Check failure stack trace: ***
Aborted_**

Kindly check this.

I am sharing my compiled model for your reference.
https://drive.google.com/file/d/1jldqsMwTKN-lIUFH5fb4iFKYDygwHAWH/view?usp=share_link
