### ISSUE TITLE
Quantify the PyTorch model

### ISSUE THREAD

**Issue by dingguodong-826** [Xilinx/Vitis-AI#384] opened 2021-04-20 09:47 UTC
Hello, I had this problem when I was quantifying the trained model with version 1.3, except that I didn't print any information.
![image](https://user-images.githubusercontent.com/57715990/115375099-0a36df00-a200-11eb-8189-ad1cb7d8835b.png)
It should be noted that there are two parts of my network that have reshape operation, but after I load the pre-trained weights, the network can print out the output information.Thank you very much!Good luck with your work.

**Comment by dingguodong-826** [comment] 2021-04-20 09:53
If you like, I can send you my code via email

**Comment by carrotandjzy** [comment] 2021-04-27 06:56
It' is caused by input ndim equal with output ndim for view op. This issue will be fixed in version 1.4.

**Comment by niuxjxlnx** [comment] 2022-02-21 07:12
Suppose the issue has been fixed in Vitis-AI 1.4. Will close it if no more response.

**Closed** 2022-02-22 08:32 UTC
